import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
    subsets: ["latin"],
    });

    const geistMono = Geist_Mono({
      variable: "--font-geist-mono",
        subsets: ["latin"],
        });

        export const metadata: Metadata = {
          title: "Create Next App",
            description: "Generated by create next app",
            };

            export default function RootLayout({
              children,
              }: Readonly<{
                children: React.ReactNode;
                }>) {
                  return (
                      <html lang="en">
                            <head>
                                    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0&icon_names=content_copy" />
                                          </head>
                                                <body
                                                        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                                                              >
                                                                    <div className="z-[-1] overflow-y-hidden overflow-x-hidden w-[100vw] h-[100vh] fixed">

                                                                    
                                                                            <div className="stars"></div>

                                                                            <div className="shooting-star"></div>

                                                                            <div className="shooting-star"></div>

                                                                            <div className="shooting-star"></div>

                                                                            <div className="shooting-star"></div>

                                                                            <div className="shooting-star"></div>
                                                                            </div>
                                                                                    {children}
                                                                                            <script src="https://cdn.lordicon.com/lordicon.js"></script>
                                                                                                  </body>
                                                                                                      </html>
                                                                                                        );
                                                                                                        }
                                                                                                        